services:
  db:
    container_name: ${APP_NAME}_DB
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: ${APP_NAME}_app
    build: .
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NUM_SHARDS=${NUM_SHARDS}
      - FLUSH_INTERVAL=${FLUSH_INTERVAL}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy

